# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/php:7.1-browsers

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mysql:9.4

    working_directory: ~/wp-avorg-plugin

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v6-dependencies-{{ checksum "composer.json" }}
        # fallback to using the latest cache if no exact match is found
        - v6-dependencies-

    - run: composer install -n --prefer-dist

    - run: ls vendor/narthur
    - run: ls vendor/narthur/natlib

    - run: sudo apt-get update && sudo apt-get install zip
    - run: zip -r wp-avorg-plugin .

    - store_artifacts:
        path: wp-avorg-plugin.zip

    - save_cache:
        paths:
        - ./vendor
        key: v6-dependencies-{{ checksum "composer.json" }}

    # run tests!
    - run: vendor/phpunit/phpunit/phpunit