version: 2.1
orbs:
  github-release: haskell-works/github-release@1.3.3
jobs:
  test:
    docker:
      - image: circleci/php:7.3.9-node-browsers

    working_directory: ~/wp-avorg-plugin

    steps:
      - checkout

      - restore_cache:
          keys:
            - v6-composer-{{ checksum "composer.lock" }}
            - v6-composer-

      - run:
          name: Install dependencies
          command: composer install --no-dev --no-interaction

      - run:
          name: Compress build
          command: |
            sudo mkdir /build
            sudo zip -r /build/wp-avorg-plugin .

      - store_artifacts:
          path: /build/wp-avorg-plugin.zip

      - persist_to_workspace:
          root: /build
          paths:
            - wp-avorg-plugin.zip

      - save_cache:
          paths:
            - ./vendor
          key: v6-composer-{{ checksum "composer.lock" }}

      - run:
          name: PHPUnit
          command: |
            curl -L -o ~/phpunit https://phar.phpunit.de/phpunit-8.phar
            chmod +x ~/phpunit
            mkdir -p ~/phpunit_results
            ~/phpunit --log-junit ~/phpunit_results/junit.xml

      - store_test_results:
          path: ~/phpunit_results

      - store_artifacts:
          path: ~/phpunit_results
  deploy:
    docker:
      - image: circleci/php:7.3.9-node-browsers

    steps:
      - add_ssh_keys:
          fingerprints:
            - "da:93:9d:ad:27:17:f0:93:58:5b:a9:fa:51:45:7e:a9"

      - checkout

      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Upload build to surge.sh
          command: |
            echo "wp-avorg-plugin-${CIRCLE_BRANCH}.surge.sh"
            npm install surge
            ./node_modules/.bin/surge --project /tmp/workspace --domain "wp-avorg-plugin-${CIRCLE_BRANCH}.surge.sh"

      - run:
          name: Deploy build to staging server
          command: |
            cp known_hosts_staging ~/.ssh/known_hosts
            scp -P 18765 /tmp/workspace/wp-avorg-plugin.zip audiove9@146.66.103.140:/home/audiove9/public_html/dev/
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            php wp-cli.phar --ssh=audiove9@146.66.103.140:18765/home/audiove9/public_html/dev/ plugin install wp-avorg-plugin.zip --activate --force
            ssh -p 18765 audiove9@146.66.103.140 'rm /home/audiove9/public_html/dev/wp-avorg-plugin.zip'
workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - dev
  my-github-release:
    jobs:
      - github-release/release:
          tag: v$CIRCLE_BUILD_NUM
          title: Release v$CIRCLE_BUILD_NUM
          artefacts-folder: /build
          filters:
            branches:
              only: master