version: 2.1
orbs:
  github-release: haskell-works/github-release@1.3.3
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-browsers

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mysql:9.4

    working_directory: ~/wp-avorg-plugin

    steps:
      # Install NPM
      - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
      - run: sudo apt-get install -y nodejs

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-composer-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-composer-

      - restore_cache:
          keys:
            - v1-npm-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-npm-

      - run:
          name: Install dependencies
          command: |
            composer install -n
            npm install

      - run:
          name: Compress build
          command: |
            sudo mkdir /build
            sudo zip -r /build/wp-avorg-plugin .

      - store_artifacts:
          path: /build/wp-avorg-plugin.zip

      - run:
          name: Upload build to surge.sh
          command: |
            echo "wp-avorg-plugin-${CIRCLE_BRANCH}.surge.sh"
            ./node_modules/.bin/surge --project /build --domain "wp-avorg-plugin-${CIRCLE_BRANCH}.surge.sh"
          filters:
            branches:
              only:
                - master
                - dev

      - save_cache:
          paths:
            - ./vendor
          key: v2-composer-{{ checksum "composer.lock" }}

      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-{{ checksum "package-lock.json" }}

      - run:
          command: |
            mkdir -p ~/phpunit
            vendor/phpunit/phpunit/phpunit --log-junit ~/phpunit/junit.xml
          when: always

      - store_test_results:
          path: ~/phpunit

      - store_artifacts:
          path: ~/phpunit
workflow:
  my-github-release:
    jobs:
      - github-release/release:
          tag: v$CIRCLE_BUILD_NUM
          title: Release v$CIRCLE_BUILD_NUM
          artefacts-folder: /build
          filters:
            branches:
              only: master