version: 2.1
orbs:
  github-release: haskell-works/github-release@1.3.3
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-browsers

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mysql:9.4

    working_directory: ~/wp-avorg-plugin

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-composer-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-composer-

      - run:
          name: Install dependencies
          command: composer install --no-dev --no-interaction

      - run:
          name: Compress build
          command: |
            sudo mkdir /build
            sudo zip -r /build/wp-avorg-plugin .

      - store_artifacts:
          path: /build/wp-avorg-plugin.zip

      - run:
          name: Upload build to surge.sh
          command: |
            echo "wp-avorg-plugin-${CIRCLE_BRANCH}.surge.sh"
            curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
            sudo apt-get install -y nodejs
            npm install surge
            ./node_modules/.bin/surge --project /build --domain "wp-avorg-plugin-${CIRCLE_BRANCH}.surge.sh"
          filters:
            branches:
              only:
                - master
                - dev

      - save_cache:
          paths:
            - ./vendor
          key: v2-composer-{{ checksum "composer.lock" }}

      - run:
          name: PHPUnit
          command: |
            curl -o ~/phpunit https://phar.phpunit.de/phpunit-8.phar
            chmod +x ~/phpunit
            mkdir -p ~/phpunit_results
            ~/phpunit --log-junit ~/phpunit_results/junit.xml

      - store_test_results:
          path: ~/phpunit_results

      - store_artifacts:
          path: ~/phpunit_results
workflow:
  my-github-release:
    jobs:
      - github-release/release:
          tag: v$CIRCLE_BUILD_NUM
          title: Release v$CIRCLE_BUILD_NUM
          artefacts-folder: /build
          filters:
            branches:
              only: master